"""empty message

Revision ID: 87779be2d324
Revises: 73688ebb9cfc
Create Date: 2022-03-13 16:04:09.829216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87779be2d324'
down_revision = '73688ebb9cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.UnicodeText(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
